<a href="https://colab.research.google.com/github/Athting/Python_libraries/blob/main/basics1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#creating numpy/n-d arrays
import numpy as np

In [8]:
arr1 = np.array([1,2,3,4,6])

In [9]:
arr1

array([1, 2, 3, 4, 6])

In [10]:
type(arr1)

numpy.ndarray

In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
type(arr2)

numpy.ndarray

In [15]:
arr3 = np.zeros((2, 3));
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr4 = np.ones((3,4));

In [17]:
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr6 = np.arange(1, 6, 2)

In [26]:
arr6

array([1, 3, 5])

In [31]:
arr7 = np.linspace(10, 20, 18);

In [32]:
arr7

array([10.        , 10.58823529, 11.17647059, 11.76470588, 12.35294118,
       12.94117647, 13.52941176, 14.11764706, 14.70588235, 15.29411765,
       15.88235294, 16.47058824, 17.05882353, 17.64705882, 18.23529412,
       18.82352941, 19.41176471, 20.        ])

In [33]:
arr8 = arr7.copy()

In [34]:
arr8

array([10.        , 10.58823529, 11.17647059, 11.76470588, 12.35294118,
       12.94117647, 13.52941176, 14.11764706, 14.70588235, 15.29411765,
       15.88235294, 16.47058824, 17.05882353, 17.64705882, 18.23529412,
       18.82352941, 19.41176471, 20.        ])