<a href="https://colab.research.google.com/github/Athting/Python_libraries/blob/main/basics2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#creating numpy/n-d arrays
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5])

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1.shape

(5,)

In [ ]:
arr2 = np.array([[1,3,4],[1,3,5]])

In [ ]:
arr2

array([[1, 3, 4],
       [1, 3, 5]])

In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
arr3.shape

(2, 2, 3)

In [ ]:
arr3.ndim

3

In [ ]:
arr2.ndim
arr1.ndim

1

In [ ]:
arr2.ndim

2

In [47]:
arr1.size

5

In [48]:
arr2.size

6

In [49]:
arr3.size

12

In [50]:
arr3.itemsize

8

In [51]:
arr2.dtype

dtype('int64')

In [52]:
arr1.dtype

dtype('int64')

In [53]:
arr2.astype('float')

array([[1., 3., 4.],
       [1., 3., 5.]])

In [58]:
arr1.astype('str_')

array(['1', '2', '3', '4', '5'], dtype='<U21')