<a href="https://colab.research.google.com/github/Athting/Python_libraries/blob/main/NumpyPart6-IndexingSlicingandIteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
arr1 = np.arange(24).reshape(3, 8)

In [11]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [12]:
arr2 = np.arange(6)
arr2

array([0, 1, 2, 3, 4, 5])

In [17]:
arr2[0]

np.int64(0)

In [18]:
arr1[2]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [20]:
arr1[:,2]

array([ 2, 10, 18])

In [21]:
arr1[:,1:3]

array([[ 1,  2],
       [ 9, 10],
       [17, 18]])

In [22]:
arr1[1:2, 1:3]

array([[ 9, 10]])

In [23]:
arr1[2:3, 0:4]

array([[16, 17, 18, 19]])

In [24]:
for i in arr1:
  print(i)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


In [25]:
for i in np.nditer(arr1):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
