<a href="https://colab.research.google.com/github/Athting/Python_libraries/blob/main/NumpyPart10-IndexingwithBooleanArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low = 1, high = 100, size = 20).reshape(4,5)
arr

array([[ 5, 91, 25, 64, 48],
       [ 8, 42, 99, 42, 94],
       [83, 50, 70, 55, 76],
       [67, 96, 93, 32, 29]])

In [3]:
arr[0]

array([ 5, 91, 25, 64, 48])

In [6]:
# Indexing using Boolean Array
arr[arr>50]

array([[False,  True, False,  True, False],
       [False, False,  True, False,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True, False, False]])

In [7]:
arr[((arr>50) & (arr%2 != 0))]

array([91, 99, 83, 55, 67, 93])

In [8]:
arr[((arr>50) & (arr%2 != 0))] = 0

In [9]:
arr

array([[ 5,  0, 25, 64, 48],
       [ 8, 42,  0, 42, 94],
       [ 0, 50, 70,  0, 76],
       [ 0, 96,  0, 32, 29]])