<a href="https://colab.research.google.com/github/Athting/Python_libraries/blob/main/NumpyPart8_ReshapingNumpyarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [26]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [27]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [30]:
arr2*2

array([ 8, 10, 12, 14, 16, 18])

In [31]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [32]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)


In [33]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [35]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [37]:
arr4.max()

np.int64(11)

In [38]:
arr4.min()

np.int64(6)

In [39]:
arr4.min(axis=0)

array([6, 7])

In [40]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [41]:
arr4.sum()

np.int64(51)

In [42]:
arr4.sum(axis=0)

array([24, 27])

In [43]:
arr4.mean()

np.float64(8.5)

In [44]:
arr4.std()

np.float64(1.707825127659933)

In [45]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [46]:
np.median(arr4)

np.float64(8.5)

In [48]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [49]:
arr4.ndim

2

In [50]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [51]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [53]:
arr5 = np.arange(12, 18).reshape(2,3)

In [54]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [56]:
np.hstack((arr3, arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [57]:
np.vstack((arr3, arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [63]:
arr3
np.hsplit(arr3, 3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [64]:
np.vsplit(arr3, 2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]